import { BaseEntity } from '../../../shared/domain/model/base-entity';
import { EnvironmentalState, MonitoredMetric } from './monitored-metric';

/**
 * Represents an action that can be executed by a container monitoring device.
 *
 * These actions define the possible actuator operations supported by the IoT platform,
 * including ventilation control, simulated cooling and servo movement.
 */
export type ActuationAction =
  | 'VENTILATION_ON'
  | 'VENTILATION_OFF'
  | 'COOLING_ON'
  | 'COOLING_OFF'
  | 'SERVO_OPEN'
  | 'SERVO_CLOSE';

/**
 * Defines the actions that can be automatically triggered by an actuation rule.
 *
 * Only activation actions are included because deactivation actions are generated
 * as a consequence of stopping a previously activated device operation.
 */
export const ACTIVATIONS: readonly ActuationAction[] = ['VENTILATION_ON', 'COOLING_ON', 'SERVO_OPEN'];

/**
 * Domain entity representing an actuation event generated by a container monitor.
 *
 * An actuation event records an automated or manual action performed by an IoT device,
 * including the environmental condition that triggered the action, execution result,
 * and the profile configuration version used at the moment of execution.
 *
 * This entity allows the platform to maintain traceability of device operations
 * and supports historical analysis of automated environmental control behavior.
 */
export class ActuationEvent implements BaseEntity {
  /**
   * Unique identifier of the actuation event.
   */
  id: number;

  /**
   * Identifier of the IoT device responsible for executing the action.
   */
  deviceId: number;

  /**
   * Identifier of the environment where the actuation event occurred.
   */
  environmentId: number;

  /**
   * Action performed by the container monitor.
   */
  action: ActuationAction;

  /**
   * Environmental metric that triggered the actuation.
   *
   * It can be null when the action was not generated by an automatic rule.
   */
  triggerMetric: MonitoredMetric | null;

  /**
   * Environmental state that caused the actuation rule to be executed.
   *
   * It can be null when no environmental condition was associated
   * with the event.
   */
  triggerState: EnvironmentalState | null;

  /**
   * Final execution status of the actuation request.
   */
  result: 'EXECUTED' | 'FAILED';

  /**
   * Timestamp indicating when the actuation event occurred.
   */
  occurredAt: string;

  /**
   * Version of the environmental profile used when the action was generated.
   *
   * This allows tracking which configuration was active during execution.
   */
  profileVersion: number | null;

  /**
   * Creates a new actuation event entity.
   *
   * @param params Properties required to initialize the actuation event.
   */
  constructor(params: {
    id: number;
    deviceId: number;
    environmentId: number;
    action: ActuationAction;
    triggerMetric: MonitoredMetric | null;
    triggerState: EnvironmentalState | null;
    result: 'EXECUTED' | 'FAILED';
    occurredAt: string;
    profileVersion: number | null;
  }) {
    this.id = params.id;
    this.deviceId = params.deviceId;
    this.environmentId = params.environmentId;
    this.action = params.action;
    this.triggerMetric = params.triggerMetric;
    this.triggerState = params.triggerState;
    this.result = params.result;
    this.occurredAt = params.occurredAt;
    this.profileVersion = params.profileVersion;
  }
}
