import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { Observable, catchError, map, of } from 'rxjs';
import { BaseApiEndpoint } from '../../shared/infrastructure/base-api-endpoint';
import { environment } from '../../../environments/environment';
import { Measurement } from '../domain/model/measurement.entity';
import { ActuationEvent } from '../domain/model/actuation-event.entity';
import { ActuationRule, EnvironmentalProfile, ThresholdInput } from '../domain/model/environmental-profile.entity';
import { MonitoredMetric } from '../domain/model/monitored-metric';
import { ActuationEventAssembler, EnvironmentalProfileAssembler, MeasurementAssembler } from './tracking-assemblers';
import {
  ActuationEventResource,
  ActuationEventsResponse,
  EnvironmentalProfileResource,
  EnvironmentalProfilesResponse,
  MeasurementResource,
  MeasurementsResponse,
} from './tracking-response';

const laboratoriesEndpointUrl = `${environment.serverBasePath}${environment.laboratoryLabsEndpointPath}`;

/**
 * Represents the target device or environment where telemetry information
 * is requested.
 *
 * The environmental device is represented with a null deviceId because
 * it belongs directly to the environment, while container monitors
 * require their own identifier.
 */
export interface DeviceTarget {
  laboratoryId: number;
  environmentId: number;
  /** Container monitor; null for the environmental device of the environment. */
  deviceId: number | null;
}

/**
 * Represents the time range used for telemetry queries.
 *
 * Both values follow ISO-8601 format to ensure consistent communication
 * between frontend and backend services.
 */
export interface TelemetryPeriod {
  from: string;
  to: string;
}

/**
 * Builds the API path for an environment or a specific container monitor.
 *
 * This helper centralizes URL generation logic depending on the target type,
 * avoiding duplicated route construction across endpoint implementations.
 *
 * @param base Base API URL.
 * @param target Environment or device target information.
 * @returns Complete resource path for the selected target.
 */
function targetPath(base: string, target: DeviceTarget): string {
  const environmentPath = `${base}/${target.laboratoryId}${environment.laboratoryEnvironmentsEndpointPath}/${target.environmentId}`;
  return target.deviceId === null
    ? environmentPath
    : `${environmentPath}${environment.containerMonitorsEndpointPath}/${target.deviceId}`;
}

/**
 * Creates query parameters required for telemetry requests.
 *
 * Includes the requested time period and optionally filters by
 * a specific monitored metric.
 *
 * @param period Telemetry time range.
 * @param metric Optional metric filter.
 * @returns HTTP query parameters.
 */
function periodParams(period: TelemetryPeriod, metric?: MonitoredMetric | null): HttpParams {
  let params = new HttpParams().set('from', period.from).set('to', period.to);
  if (metric) params = params.set('metric', metric);
  return params;
}

/**
 * Endpoint responsible for retrieving IoT telemetry measurements.
 *
 * Provides access to environmental readings generated by:
 * - Environmental devices.
 * - Container monitoring devices.
 *
 * The endpoint converts API resources into domain Measurement entities
 * using the corresponding assembler.
 */
export class MeasurementApiEndpoint extends BaseApiEndpoint<
  Measurement,
  MeasurementResource,
  MeasurementsResponse,
  MeasurementAssembler
> {
  constructor(http: HttpClient) {
    super(http, laboratoriesEndpointUrl, new MeasurementAssembler());
  }

  /**
   * Retrieves measurements from an IoT device during a selected period.
   *
   * @param target Device or environment identifier.
   * @param period Requested telemetry period.
   * @param metric Optional metric filter.
   * @returns Observable containing measurement domain entities.
   */
  getMeasurements(
    target: DeviceTarget,
    period: TelemetryPeriod,
    metric?: MonitoredMetric | null,
  ): Observable<Measurement[]> {
    const url = `${targetPath(this.endpointUrl, target)}${environment.trackingTelemetryMeasurementsEndpointPath}`;
    return this.http.get<MeasurementResource[]>(url, { params: periodParams(period, metric) }).pipe(
      map((resources) =>
        resources.map((resource) => this.assembler.toEntityFromResource(resource)),
      ),
      catchError(this.handleError('Failed to fetch the readings')),
    );
  }
}

/**
 * Endpoint responsible for retrieving actuation history
 * generated by container monitoring devices.
 *
 * Provides historical information about automated device actions
 * executed according to environmental conditions.
 */
export class ActuationEventApiEndpoint extends BaseApiEndpoint<
  ActuationEvent,
  ActuationEventResource,
  ActuationEventsResponse,
  ActuationEventAssembler
> {
  constructor(http: HttpClient) {
    super(http, laboratoriesEndpointUrl, new ActuationEventAssembler());
  }

  /**
   * Retrieves actuation events within a specific time period.
   *
   * @param target Container monitor identifier.
   * @param period Requested event period.
   * @returns Observable containing actuation event entities.
   */
  getActuationEvents(target: DeviceTarget, period: TelemetryPeriod): Observable<ActuationEvent[]> {
    const url = `${targetPath(this.endpointUrl, target)}${environment.trackingActuationEventsEndpointPath}`;
    return this.http.get<ActuationEventResource[]>(url, { params: periodParams(period) }).pipe(
      map((resources) =>
        resources.map((resource) => this.assembler.toEntityFromResource(resource)),
      ),
      catchError(this.handleError('Failed to fetch the actions of the container monitor')),
    );
  }
}

/**
 * Endpoint responsible for managing environmental profile configuration.
 *
 * Handles:
 * - Retrieving active environmental profiles.
 * - Updating metric thresholds.
 * - Updating automatic actuation rules.
 *
 * Profile data is transformed into EnvironmentalProfile domain entities
 * through the configured assembler.
 */
export class EnvironmentalProfileApiEndpoint extends BaseApiEndpoint<
  EnvironmentalProfile,
  EnvironmentalProfileResource,
  EnvironmentalProfilesResponse,
  EnvironmentalProfileAssembler
> {
  constructor(http: HttpClient) {
    super(http, laboratoriesEndpointUrl, new EnvironmentalProfileAssembler());
  }

  /**
   * Retrieves the active environmental profile.
   *
   * Returns null when the profile has not been configured yet.
   *
   * @param target Environment or device target.
   * @returns Observable containing the environmental profile.
   */
  getProfile(target: DeviceTarget): Observable<EnvironmentalProfile | null> {
    return this.http.get<EnvironmentalProfileResource>(this.profileUrl(target)).pipe(
      map((resource): EnvironmentalProfile | null => this.assembler.toEntityFromResource(resource)),
      catchError((error: HttpErrorResponse) =>
        error.status === 404
          ? of(null)
          : this.handleError('Failed to fetch the environmental profile')(error),
      ),
    );
  }

  /**
   * Updates environmental threshold configurations.
   *
   * Threshold updates define the acceptable measurement ranges
   * used to evaluate environmental conditions.
   *
   * @param target Environment or device target.
   * @param thresholds Threshold configuration values.
   * @returns Observable containing the updated environmental profile.
   */
  updateThresholds(
    target: DeviceTarget,
    thresholds: ThresholdInput[],
  ): Observable<EnvironmentalProfile> {
    return this.http
      .put<EnvironmentalProfileResource>(
        `${this.profileUrl(target)}${environment.trackingThresholdsEndpointPath}`,
        { thresholds },
      )
      .pipe(
        map((resource) => this.assembler.toEntityFromResource(resource)),
        catchError(this.handleError('Failed to save the thresholds')),
      );
  }

  /**
   * Updates automatic actuation rules.
   *
   * These rules define device actions triggered by abnormal
   * environmental conditions.
   *
   * @param target Target device.
   * @param rules Actuation rules configuration.
   * @returns Observable containing the updated environmental profile.
   */
  updateActuationRules(
    target: DeviceTarget,
    rules: ActuationRule[],
  ): Observable<EnvironmentalProfile> {
    return this.http
      .put<EnvironmentalProfileResource>(
        `${this.profileUrl(target)}${environment.trackingActuationRulesEndpointPath}`,
        { rules },
      )
      .pipe(
        map((resource) => this.assembler.toEntityFromResource(resource)),
        catchError(this.handleError('Failed to save the actuation rules')),
      );
  }

  /**
   * Builds the URL used for environmental profile operations.
   *
   * @param target Environment or device target.
   * @returns Complete profile endpoint URL.
   */
  private profileUrl(target: DeviceTarget): string {
    return `${targetPath(this.endpointUrl, target)}${environment.trackingEnvironmentalProfileEndpointPath}`;
  }
}
